### ISSUE TITLE
Fatally missing blocks and items error on joining world generated with block armor (even with mod armors from pack disabled)

### ISSUE THREAD

**Issue by Hellcommander** [2piradians/Block-Armor#10]
Having block armor mod enabled will make a fatally missing blocks and items error on joining a multiplayer server that had its world created with block armor enabled (tested with mod block armor on and off)
[fml-server-latest.zip](https://github.com/2piradians/Block-Armor/files/1164030/fml-server-latest.zip)
[latest.zip](https://github.com/2piradians/Block-Armor/files/1164036/latest.zip)
[fml-junk-earlystartup.zip](https://github.com/2piradians/Block-Armor/files/1164038/fml-junk-earlystartup.zip)

**Comment by Furgl** [comment]
Thank you for reporting this! This issue should be fixed in 2.4.5, please let us know if it is not.
