### ISSUE TITLE
Still have same issue of Fatally missing blocks and items error on joining world generated with block armor (even with mod armors from pack disabled)

### ISSUE THREAD

**Issue by Hellcommander** [2piradians/Block-Armor#11]
Same error that i posted hours ago (you did fix some of the missing such and such errors though)
might help to fix the following errors:Registry Item: Found a missing id from the world blockarmor,purpur_0_helm
blockarmor,purpur_0_leggings
blockarmor,purpur_0_chestplate
blockarmor,purpur_0_boots
[fml-server-latest.zip](https://github.com/2piradians/Block-Armor/files/1164390/fml-server-latest.zip)
[latest.zip](https://github.com/2piradians/Block-Armor/files/1164391/latest.zip)
[fml-junk-earlystartup.zip](https://github.com/2piradians/Block-Armor/files/1164392/fml-junk-earlystartup.zip)
and if this is of use here is the client profiles client log
[fml-client-latest.zip](https://github.com/2piradians/Block-Armor/files/1164396/fml-client-latest.zip)
[latest.zip](https://github.com/2piradians/Block-Armor/files/1164397/latest.zip)
[fml-junk-earlystartup.zip](https://github.com/2piradians/Block-Armor/files/1164399/fml-junk-earlystartup.zip)

**Comment by Furgl** [comment]
The issue that I'm guessing is happening is that your client config is set to not create/register the hardened clay armor set (as seen at the bottom of the last fml-junk-earlystartup.zip file). This set is enabled on the server that you are connecting to, so your client is giving you an error when it tries to connect. To fix this, set the _Register Disabled Items_ option to true in your client's config and restart. This will make your client register any disabled items (i.e. the hardened clay armor set) and allow you to connect to the server. The server's config will then sync to your client when you connect.

Let us know if that fixes your issue!

**Comment by 2piradians** [comment]
Assuming this is fixed. If not the case, this issue can be reopened.
