### ISSUE TITLE
Elytra + Slimy Effect = Ridiculous flight speed

### ISSUE THREAD

**Issue by StardustAlpha** [2piradians/Block-Armor#13]
Using the [SLIMEY](https://www.youtube.com/watch?v=dWqlD_2vsOA) effect and flying with an elytra breaks the game. Not only do you go VERY FAST, but if you fly outside of the loaded chunks, the game lags a LOT.
[VIDEO](https://www.youtube.com/watch?v=87r31FwbJ4I&feature=youtu.be)
Block Armor Version: 2.4.6
Other installed mods: Minecraft 1.12, Forge 14.22.0.2465
To reproduce:
Set 'armor pieces needed for effects' to 1
Make new world [creative mode]
Equip elytra and slime block leggings
Fly

**Comment by Furgl** [comment]
Thanks for the report (and nice slimey reference)! This is fixed in v2.4.7: 
[BlockArmor-1.12-2.4.7.jar.zip](https://github.com/2piradians/Block-Armor/files/1265592/BlockArmor-1.12-2.4.7.jar.zip)
