### ISSUE TITLE
Latest version doesn't work in 1.12.1

### ISSUE THREAD

**Issue by mcdodge34** [2piradians/Block-Armor#17]
Please, fix this pretty please, I need it for 1.12.1, for some reasons I have multiple problems with some mods that don't want to work in 1.12.2, all works #1 in 1.12.1 but for just an example, I get random CTD when trying to connect to my server in 1.12.2, and also I tried every single armor piece (vanilla armor to be sure its not your mod), none of them show me any armor bar on top of the hearts, and the armor seems to be useless against mobs. If I could guess which mod cause this, I would remove it and move along.

**Comment by Furgl** [comment]
This has been fixed in v2.4.10: [BlockArmor-1.12.2-2.4.10.jar.zip](https://github.com/2piradians/Block-Armor/files/1341517/BlockArmor-1.12.2-2.4.10.jar.zip)
Thanks for reporting this!

**Comment by mcdodge34** [comment]
Awesome, its getting irritating to see all the funky block armor stuff in JEI/NEI right now, glad its now fixed since I think it will take awhile for my issue to be corrected in 1.12.2. I check every week to see after updating all mods to their latest version in a test instance and so far, armor bar doesn't show and I instant CTD when I want to join my test 1.12.2 server with the same mod I have in 1.12.1.
