### ISSUE TITLE
Obsidian armor recipe conflicts my obsidian armor recipe

### ISSUE THREAD

**Issue by NoahJelen** [2piradians/Block-Armor#20]
The mod that I made also has a recipe for its own obsidian and whenever I use it with this mod and disable this mod's obsidian armor crafting recipe, it also disables mine (I use the resource pack method for my recipes). Do you guys have a workaround for this?
If you need to look at my mod's source, here is the repository:https://github.com/NoahJelen/nnparadisemod/tree/1.12.2

**Comment by Furgl** [comment]
I would suggest that you look at other mods that can assist with conflicting recipes; like [NoMoreRecipeConflict](https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict) or [CraftTweaker](https://minecraft.curseforge.com/projects/crafttweaker?gameCategorySlug=mc-mods&projectID=239197).
