### ISSUE TITLE
How do I forcefully enable an armor set?

### ISSUE THREAD

**Issue by NoahJelen** [2piradians/Block-Armor#21]
I am trying to enable the vanilla furnace armor set from the config GUI and every time I restart minecraft, It's disabled again! How do I force Block Armor to enable an armor set?

**Comment by Furgl** [comment]
Vanilla furnace armor is enabled by default. Block Armor will automatically disable any armors that it can't find textures for, so that shouldn't be the case with vanilla furnaces unless you have a strange resource pack or mod interfering.

**Comment by NoahJelen** [comment]
I managed to fix my issue. It was an issue with a resource pack I made. As a suggestion, can you please add a config option that would prevent Block Armor from disabling anything?

**Comment by Furgl** [comment]
If Block Armor did not disable armor that it cannot find textures for, then there would be many armors, especially in mod packs, that are just checkered black and purple. I do not plan on allowing that.
