### ISSUE TITLE
[1.12] crash when loading world "Ticking memory connection"

### ISSUE THREAD

**Issue by ProxyPlayerHD** [2piradians/Block-Armor#22]
[CRASH LOG](https://pastebin.com/Btt5J5jN)

the log should contain all information needed.

all i did was try to load a world with the mod, when i uninstall it everything works fine

**Comment by Excaliburning** [comment]
Hello !

Same issue over here.
https://gist.github.com/Excaliburning/a5d0f7aa67445e292a89a2f8b47552b4

**Comment by ProxyPlayerHD** [comment]
Still have this bug.

how is this not fixed already? is there anyone still working on this mod?

https://pastebin.com/E390FHxx

**Comment by AZbadfish** [comment]
Same problem here.

**Comment by MusicMaestro123** [comment]
Same here

**Comment by Furgl** [comment]
Fixed in v2.4.12
