### ISSUE TITLE
[Possible mod conflict] Block Armor does not play nice with Quark (v1.5-150)

### ISSUE THREAD

**Issue by NoahJelen** [2piradians/Block-Armor#24]
I am trying to launch the latest version of Block Armor with Quark and it keeps crashing on me.

The computer I am trying to launch Block Armor on:
OS: Arch Linux x86_64
Processor: Intel core i3 (dual core) @2.4Ghz
RAM: 16GB DDR4 @ 2133Mhz
Storage: 1TB SSD

Minecraft Version:1.12.2
Forge Version: 14.23.5.2836
Other mods installed:
Galacticraft
Dynamic Surroundings
Aether Legacy
JEI
Effortless Building
Extra Rails
WAILA
Iron Chest
More Planets (Galacticraft addon)
Nether Noah's Paradise Mod (I made this one)
Quark
Quark Oddities
Redstone Paste
Toro Health
Vanilla Fix
World Edit
Xaero's Minmap
Xaero's Worldmap

The crash report is below:
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2019-05-08 14:33:15 MST
Description: Initializing game

java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to net.minecraft.item.ItemBlock
    at twopiradians.blockArmor.common.item.ArmorSet.<init>(ArmorSet.java:145)
    at twopiradians.blockArmor.common.item.ArmorSet.postInit(ArmorSet.java:231)
    at twopiradians.blockArmor.common.item.ModItems$RegistrationHandler.registerItems(ModItems.java:33)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_RegistrationHandler_registerItems_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 5.0.13-arch1-1-ARCH
  Java Version: 1.8.0_212, Oracle Corporation
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 6793402400 bytes (6478 MB) / 8342470656 bytes (7956 MB) up to 8342470656 bytes (7956 MB)
  LiteLoader Brand: LiteLoader startup incomplete
  LiteLoader Mods: LiteLoader startup incomplete
  LaunchWrapper: 31 active transformer(s)
                           - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
                           - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
                           - Transformer: optifine.OptiFineClassTransformer
                           - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
                           - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
                           - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
                           - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
                           - Transformer: $wrapper.micdoodle8.mods.miccore.MicdoodleTransformer
                           - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
                           - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
                           - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
                           - Transformer: $wrapper.cubex2.cxlibrary.CoreModTransformer
                           - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
                           - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
                           - Transformer: micdoodle8.mods.miccore.MicdoodleAccessTransformer
                           - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
                           - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
                           - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockTransformer
                           - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockSpecialTransformer
                           - Transformer: net.minecraftforge.fml.common.asm.transformers.PotionEffectTransformer
                           - Transformer: $wrapper.vazkii.quark.base.asm.ClassTransformer
                           - Transformer: $wrapper.net.fybertech.nwr.NWRTransformer
                           - Transformer: $wrapper.org.orecruncher.dsurround.asm.Transformer
                           - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
                           - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
                           - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
                           - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
                           - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
                           - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
                           - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
                           - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
  JVM Flags: 2 total; -Xms8192m -Xmx8192m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2836 Optifine OptiFine_1.12.2_HD_U_E3 31 mods loaded, 31 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                  | Version           | Source                                            | Signature                                |
       |:----- |:------------------- |:----------------- |:------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft           | 1.12.2            | minecraft.jar                                     | None                                     |
       | LCH   | mcp                 | 9.42              | minecraft.jar                                     | None                                     |
       | LCH   | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2836-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge               | 14.23.5.2836      | forge-1.12.2-14.23.5.2836-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | micdoodlecore       |                   | minecraft.jar                                     | None                                     |
       | LCH   | dsurroundcore       | 3.5.4.3           | minecraft.jar                                     | None                                     |
       | LCH   | aether_legacy       | 1.4.4             | aether_legacy-1.12.2-v1.4.4.jar                   | None                                     |
       | LCH   | jei                 | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                         | None                                     |
       | LCH   | quark               | r1.5-150          | Quark-r1.5-150.jar                                | None                                     |
       | LCH   | autoreglib          | 1.3-28            | AutoRegLib-1.3-28.jar                             | None                                     |
       | LCH   | blockarmor          | 2.4.11            | BlockArmor-1.12.2-2.4.11.jar                      | None                                     |
       | LCH   | cxlibrary           | 1.6.1             | cxlibrary-1.12.1-1.6.1.jar                        | None                                     |
       | LCH   | effortlessbuilding  | 1.0.3             | effortlessbuilding-1.0.3.jar                      | None                                     |
       | LCH   | shadowmc            | 3.8.0             | ShadowMC-1.12-3.8.0.jar                           | None                                     |
       | LCH   | extrarails          | 1.3.0             | ExtraRails-1.12-1.3.0.jar                         | None                                     |
       | LCH   | galacticraftcore    | 4.0.2.210         | GalacticraftCore-1.12.2-4.0.2.210.jar             | None                                     |
       | LCH   | galacticraftplanets | 4.0.2.210         | Galacticraft-Planets-1.12.2-4.0.2.210.jar         | None                                     |
       | LCH   | waila               | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
       | LCH   | ironchest           | 1.12.2-7.0.59.842 | ironchest-1.12.2-7.0.59.842.jar                   | None                                     |
       | LCH   | moreplanets         | 2.0.18            | More-Planets-1.12.2-2.0.18-GC190.jar              | b3468b224a74e296555ad7efeb35f482e6f445de |
       | LCH   | morefurnaces        | 1.10.5            | MoreFurnaces-1.12.2-1.10.6.jar                    | None                                     |
       | LCH   | nnparadisemod       | 1.4 (Update 2019) | nnparadisemod-1.4 (Update 2019).jar               | None                                     |
       | LCH   | quarkoddities       | 1                 | QuarkOddities-1.12.2.jar                          | None                                     |
       | LCH   | redstonepaste       | 1.7.5             | redstonepaste-mc1.12-1.7.5.jar                    | None                                     |
       | LCH   | torohealthmod       | 1.12.2-11         | torohealth-1.12.2-11.jar                          | None                                     |
       | LCH   | vanillafix          | 1.0.10-SNAPSHOT   | VanillaFix-1.0.10-99.jar                          | None                                     |
       | LCH   | worldedit           | 6.1.10-SNAPSHOT   | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
       | LCH   | xaerominimap        | 1.16              | Xaeros_Minimap_1.16_Forge_1.12.jar                | None                                     |
       | LCH   | xaeroworldmap       | 1.3.3             | XaerosWorldMap_1.3.3_Forge_1.12.jar               | None                                     |
       | LCH   | orelib              | 3.5.2.2           | OreLib-1.12.2-3.5.2.2.jar                         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | dsurround           | 3.5.4.3           | DynamicSurroundings-1.12.2-3.5.4.3.jar            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
  Loaded coremods (and transformers): Quark Plugin (Quark-r1.5-150.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.210.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
                                        cubex2.cxlibrary.CoreModTransformer
                                      NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
                                        net.fybertech.nwr.NWRTransformer
                                      DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
                                        org.orecruncher.dsurround.asm.Transformer
  Suspected Mods: Block Armor (blockarmor)
  Launched Version: MultiMC5
  LWJGL: 2.9.4
  OpenGL: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2)  GL version 3.0 Mesa 19.0.3, Intel Open Source Technology Center
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Nether Noah (Mod Support), Nether Noah
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz

**Comment by NoahJelen** [comment]
I managed to isolate this to an issue with Quark by removing all my mods (except for Forge) and installing them again, one by one.

**Comment by Furgl** [comment]
Fixed in v2.4.12
