### ISSUE TITLE
Hard incompatibility between Block Armor and Apotheosis' Garden module

### ISSUE THREAD

**Issue by jtgibson01** [2piradians/Block-Armor#25]
Originally reported here for Apotheosis, some text repeated for simplicity: https://github.com/Shadows-of-Fire/Apotheosis/issues/80

There is a hard incompatibility between Block Armor and Apotheosis.

[crash-2019-08-19_03.07.18-client.txt](https://github.com/2piradians/Block-Armor/files/3523599/crash-2019-08-19_03.07.18-client.txt)

Block Armor digs up textures from other mod data, but the Garden module of Apotheosis does not provide those textures in a fashion that Block Armor can read. Bad Things ensue.

The author of Apotheosis claims that this is due to Block Armor not respecting a Forge graphical registry feature:
> The only fix for this is for BA to use IRegistryDelegate in place of Item for this list: https://github.com/2piradians/Block-Armor/blob/1.12.2/src/main/java/twopiradians/blockArmor/common/item/ArmorSet.java#L76
> This is not an error caused by me, or resolvable by me, as BA is not respecting an existing forge feature (registry replacement).

It appears that it would be an easy fix if all that is required is to target a class interface rather than a specific child class, though of course nothing is ever that simple. =)

**Comment by Furgl** [comment]
Should be fixed by now. I was able to load up Apotheosis and Block Armor without issue
