### ISSUE TITLE
Armour Looks Weird

### ISSUE THREAD

**Issue by sukoshiotokonoko** [2piradians/Block-Armor#30]
![2020-08-26_15 27 03](https://user-images.githubusercontent.com/69873721/91347641-ac591100-e7b0-11ea-85f3-34d7c8239684.png)
![2020-08-26_15 27 16](https://user-images.githubusercontent.com/69873721/91347677-b4b14c00-e7b0-11ea-9899-af25a8508049.png)
![2020-08-26_15 27 10](https://user-images.githubusercontent.com/69873721/91347681-b713a600-e7b0-11ea-87e3-55ceaab0e6b5.png)

**Comment by Furgl** [comment]
Block Armor is not compatible with mods that change the player model
