### ISSUE TITLE
armors won't appear in craftarea

### ISSUE THREAD

**Issue by RAhin0** [2piradians/Block-Armor#31]
i use jei mod and when i check the craft there are none.
![Screenshot (17)](https://user-images.githubusercontent.com/82463031/114582806-c3e2fc80-9ca2-11eb-9d68-dc46e98b7d41.png)

**Comment by Furgl** [comment]
Do you have any other mods installed? And could you send your logs?

**Comment by Furgl** [comment]
Hopefully fixed in v2.6.1 - could you please test it again?
