### ISSUE TITLE
no manifest attribute

### ISSUE THREAD

**Issue by trainperson174** [2piradians/Block-Armor#32]
can anyone help me? i tried to run it wiht java and it didnt work, so i made a .bat file to run it with and it says this
![caca](https://user-images.githubusercontent.com/82597617/114889404-18d45f00-9dd8-11eb-85ba-8e2a9b1ae646.png)

**Comment by Furgl** [comment]
You're trying to run the .jar file? You have to install the mod with Forge: https://www.instructables.com/How-to-Install-Mods-for-Minecraft-Forge/

**Comment by trainperson174** [comment]
> You're trying to run the .jar file? You have to install the mod with Forge: https://www.instructables.com/How-to-Install-Mods-for-Minecraft-Forge/

ohh i didnt know that, thanks!
