### ISSUE TITLE
Minecraft 1.16.5 Block Armor and JEI

### ISSUE THREAD

**Issue by CanBoy67** [2piradians/Block-Armor#33]
The Minecraft 1.16.5 version of block armor along with jei makes JEI inaccessible so I am unable to see the recipes for block armor

**Comment by Furgl** [comment]
What mods do you have installed? Could you send your latest.log?

**Comment by CanBoy67** [comment]
I doubt if it'll be of any use but [here](https://gist.github.com/CanBoy67/3b8fcc684d3d9db0e592e8d43d4155e7) you go

**Comment by Furgl** [comment]
Hopefully fixed in v2.6.1 - could you please test it again?

**Comment by CanBoy67** [comment]
Just tested it with jei and the update worked thank you
