### ISSUE TITLE
Incompatibility with Mekanism

### ISSUE THREAD

**Issue by JadeKaiser** [2piradians/Block-Armor#34]
I tried just adding this into one of the collections of mods that I already use, and got an error during the "load registries event phase" of initially starting up MC. Since I'm not very "literate" as far as reading and understanding the logs goes, I tried turning off all my other mods and then adding them back in a few at a time, and was able to narrow it down to the Mekanism mod that was causing the incompatibility.

Probably not something you need to go to great length to fix, but I figured I should let you know. At least now you can make a note for other people that there's an incompatibility issue there, if nothing else.

**Comment by Furgl** [comment]
Fixed in v2.6.1 - thanks for reporting it!
