### ISSUE TITLE
(glitch) I crash whenever I use health boost armour.

### ISSUE THREAD

**Issue by Frey74** [2piradians/Block-Armor#36]
I got Obsidian armour but whenever I use it I crash. Same thing happens if I die whilst wearing ANY armour from the Block Armour  mod. I know this is because somehow the games registering the new hearts and a death as a similar thing, but when I die I can just join back, while if I put on 2 pieces obsidian armour, I crash completely, and have to delete the mod, go back in the server, and reinstall the mod. Anyways, I cant use any Healthboost armour. Heres my log:
https://github.com/2piradians/Block-Armor/files/6490257/latest.log   . Please tell me if another mod is doing this or something else. Thanls

**Comment by Frey74** [comment]
Im guessing the reason I crash is the death thing combined with the the effects u get from the armour. In fact, ive tested it several times, its only when I use 2 or more armour pieces.

**Comment by Furgl** [comment]
Something is messing with enchantments. What mods do you have that could be changing enchantments?

**Comment by Frey74** [comment]
Apotheosis, most likely I can think of.

**Comment by Frey74** [comment]
Ill try the mod without it

**Comment by Frey74** [comment]
It works now thanks!

**Comment by Furgl** [comment]
This issue with Apotheosis is fixed in v2.6.2 - thanks for reporting it!
