### ISSUE TITLE
chest armor is overloading server

### ISSUE THREAD

**Issue by CashCow4** [2piradians/Block-Armor#37]
The chest armor is crashing my server because it is creating too large of a NBT tag for the items. Can you tell me where the file is located that has the inventory of each piece of chest armor?

**Comment by Furgl** [comment]
You would need to edit your world save file with a level editor. Can you post your crash log?

**Comment by yusufgood0** [comment]
you can also go into appdata/roaming/.minecraft/saves/(world)/playerdata and delete your player file

**Comment by Furgl** [comment]
No response - closing
