### ISSUE TITLE
Config Generates Blank

### ISSUE THREAD

**Issue by WenXin20** [2piradians/Block-Armor#4]
Block Armor v2.4.1
Forge 1.10.2-2254

After installing the new update, I deleted the old config file for the new update, but it regenerated the config file blank. I also tried using the old config, but it doesn't read it, probably since the format is different now.

**Comment by Furgl** [comment]
I just tested this with the same Block Armor and Forge versions with the config file deleted and it generates it normally. Do you have other mods installed that may be interfering?

**Comment by WenXin20** [comment]
Actually, it looks like it reached max ids before generating the config completely, since it's set to generate the disabled armors by default, so it crashed with the 'Max IDs reached' before the config cold generate properly. I tried it with just a few mods and it worked fine.

**Comment by Furgl** [comment]
Load Block Armor, without the hundreds of other mods, so that it can generate the config normally and then change the config option "Register disabled items" to false and disable any sets that you don't want. That will stop the disabled items from being registered.

**Comment by WenXin20** [comment]
Ok, thanks
