### ISSUE TITLE
Block Armor crashes with FramedBlocks

### ISSUE THREAD

**Issue by nekomaster** [2piradians/Block-Armor#42]
So yeah, the game crashes with those two mods.

Running Block ARmor with MC 1.18.1 w/ Minecraft FOrge 39.0.5

Mods:
BlockArmor-1.18.1-2.6.6.jar
FramedBlocks-4.0.1.jar

Other than that the game runs with all the other mods I've tried but I ended up widdling it down to just FramedBlocks causing the render crash.

here are the logs for you to look through.
[latest.log](https://github.com/2piradians/Block-Armor/files/7738754/latest.log)
[debug.log](https://github.com/2piradians/Block-Armor/files/7738755/debug.log)
[crash-2021-12-17_23.54.41-client.txt](https://github.com/2piradians/Block-Armor/files/7738756/crash-2021-12-17_23.54.41-client.txt)

**Comment by Furgl** [comment]
Fixed in v2.6.8, thank you for reporting!
