### ISSUE TITLE
Chain command armor

### ISSUE THREAD

**Issue by Ninjaboi875** [2piradians/Block-Armor#47]
Chain command block armor or really any command block armor doesnt do its ability.

I found this on 1.16.5 and then I checked on the latest ver.

**Comment by Cod1ngGamer** [comment]
I have the same problem. My theory is it requires a second mod, like TickRateChanger.

**Comment by Cod1ngGamer** [comment]
wait, actually it just changes the day/night cycle. Much less exciting than stopping all time.

**Comment by Ninjaboi875** [comment]
Well, yes but problem, I tested all of the command block armors, none of them did anything except play a sound. Literally NOTHING happened. The tick rate changer mod might be needed, although I didnt see it in a dependency so its a bit weird.

**Comment by Furgl** [comment]
No dependencies. The command block armors speed up/reverse/stop the day night cycle while the button is held down.

**Comment by Ninjaboi875** [comment]
thats boring

**Comment by Ninjaboi875** [comment]
lemme check this

**Comment by Ninjaboi875** [comment]
boring as heck tho
