### ISSUE TITLE
Client Gets Booted from MP Server

### ISSUE THREAD

**Issue by Jo-Mamma75** [2piradians/Block-Armor#5]
Updated FoolCraft with the 2.4.1 version of BlockArmor, try to connect with a matching client and the client gets immediately booted.  I unfortunately cannot provide my log at this moment but I could reproduce the problem if need be.  I didn't crash the server or my client so all I would be able to show would be what I see in the logging in my client.  Hopefully, that will be enough to point you in a direction.

**Comment by Furgl** [comment]
Fixed in v2.4.2, thanks for telling us!
