### ISSUE TITLE
[BlockArmor-1.10.2-2.4.3]Crash when done loading

### ISSUE THREAD

**Issue by BuckTheWeasel** [2piradians/Block-Armor#8]
crashes when done loading.

error log here : https://pastebin.com/xnh8K652

checked without Block Armor Works fine.

Minecraft Version : 1.10.2
Forge Version : 12.18.3.2297

**Comment by 2piradians** [comment]
Please update to v2.4.3 and try again to see if you still get the issue (crash report says you are using v2.4.2).

**Comment by Furgl** [comment]
If the crash still happens with the updated version, please try to replicate it with less mods/no other mods installed. The crash may only happen when Block Armor is installed, but it may not be directly caused by Block Armor.

**Comment by BuckTheWeasel** [comment]
@2piradians @Furgl Woeps sorry i updated it XD and it still crashes with the same crash log above however after long mods removing and adding i found the mod that causes to crash Xtones seem to be the problem.

**Comment by Furgl** [comment]
I loaded up MC with just Xtones and Block Armor without any troubles. Can you replicate the crash with just a couple mods loaded?

**Comment by BuckTheWeasel** [comment]
-snip-

**Comment by BuckTheWeasel** [comment]
So after a lot of testing it seems to be Randomly that the crash will happen because when i when i reload my minecraft  modpack a couple of times  sometimes it works sometimes it don't 

i don't have this when i create a new modpack with 62 mods (include Xtones) 
So this going to take a lot of time to find out why this happens.

anyway guys thanks for the help 👍

**Comment by 2piradians** [comment]
No worries. If you find a way to consistently make it crash regarding Block Armor, let us know and we will work on a fix for it.
